name:                api
version:             0.1.0.0
github:              "githubuser/api"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/api#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- servant
- aeson
- wai
- wai-cors
- warp
- text
- parsec
- http-conduit
- bytestring
- http-client
- http-client-tls
- http-types
- servant
- servant-server
- yaml
- time
- parsec
- case-insensitive
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
    - servant
    - servant-server
    - wai
    - wai-cors
    - warp
    - aeson
    - text

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
